/**
 * Mermaid Editor Color Theme Presets
 * Centralized color constants for theme customization
 */

export interface ColorTheme {
  name: string;
  previewBg: string;
  nodeColor: string;
  borderColor: string;
  arrowColor: string;
  textColor: string;
  decisionBg?: string;
  decisionBorder?: string;
  decisionText?: string;
}

export const MERMAID_COLOR_THEMES: Record<string, ColorTheme> = {
  default: {
    name: 'Modern Blue',
    previewBg: '#f8fafc',
    nodeColor: '#3b82f6',
    borderColor: '#1d4ed8',
    arrowColor: '#60a5fa',
    textColor: '#ffffff',
    decisionBg: '#ffffff',
    decisionBorder: '#1d4ed8',
    decisionText: '#1d4ed8',
  },
  ocean: {
    name: 'Ocean Breeze',
    previewBg: '#f0f9ff',
    nodeColor: '#0ea5e9',
    borderColor: '#0369a1',
    arrowColor: '#38bdf8',
    textColor: '#ffffff',
    decisionBg: '#ffffff',
    decisionBorder: '#0369a1',
    decisionText: '#0369a1',
  },
  sunset: {
    name: 'Sunset Glow',
    previewBg: '#fff7ed',
    nodeColor: '#f97316',
    borderColor: '#c2410c',
    arrowColor: '#fb923c',
    textColor: '#ffffff',
    decisionBg: '#ffffff',
    decisionBorder: '#c2410c',
    decisionText: '#c2410c',
  },
  forest: {
    name: 'Forest Green',
    previewBg: '#f0fdf4',
    nodeColor: '#22c55e',
    borderColor: '#15803d',
    arrowColor: '#4ade80',
    textColor: '#ffffff',
    decisionBg: '#ffffff',
    decisionBorder: '#15803d',
    decisionText: '#15803d',
  },
  purple: {
    name: 'Purple Dream',
    previewBg: '#faf5ff',
    nodeColor: '#a855f7',
    borderColor: '#7c3aed',
    arrowColor: '#c084fc',
    textColor: '#ffffff',
    decisionBg: '#ffffff',
    decisionBorder: '#7c3aed',
    decisionText: '#7c3aed',
  },
  rose: {
    name: 'Rose Garden',
    previewBg: '#fff1f2',
    nodeColor: '#f43f5e',
    borderColor: '#be123c',
    arrowColor: '#fb7185',
    textColor: '#ffffff',
    decisionBg: '#ffffff',
    decisionBorder: '#be123c',
    decisionText: '#be123c',
  },
  dark: {
    name: 'Dark Mode',
    previewBg: '#1f2937',
    nodeColor: '#4b5563',
    borderColor: '#6b7280',
    arrowColor: '#9ca3af',
    textColor: '#f9fafb',
    decisionBg: '#374151',
    decisionBorder: '#6b7280',
    decisionText: '#f9fafb',
  },
  neon: {
    name: 'Neon Night',
    previewBg: '#0f172a',
    nodeColor: '#06b6d4',
    borderColor: '#0891b2',
    arrowColor: '#22d3ee',
    textColor: '#ffffff',
    decisionBg: '#1e293b',
    decisionBorder: '#0891b2',
    decisionText: '#22d3ee',
  },
  smoky: {
    name: 'Smoky Essence',
    previewBg: '#09090b',
    nodeColor: 'rgba(255, 255, 255, 0.1)',
    borderColor: 'rgba(255, 255, 255, 0.5)',
    arrowColor: '#a1a1aa',
    textColor: '#ffffff',
    decisionBg: 'rgba(255, 255, 255, 0.05)',
    decisionBorder: 'rgba(255, 255, 255, 0.3)',
    decisionText: '#e4e4e7',
  },
  pastel: {
    name: 'Pastel Dreams',
    previewBg: '#fefce8',
    nodeColor: '#eab308',
    borderColor: '#ca8a04',
    arrowColor: '#facc15',
    textColor: '#ffffff',
    decisionBg: '#ffffff',
    decisionBorder: '#ca8a04',
    decisionText: '#ca8a04',
  },
  monochrome: {
    name: 'Monochrome',
    previewBg: '#f9fafb',
    nodeColor: '#6b7280',
    borderColor: '#374151',
    arrowColor: '#9ca3af',
    textColor: '#ffffff',
    decisionBg: '#ffffff',
    decisionBorder: '#374151',
    decisionText: '#374151',
  },
  mint: {
    name: 'Mint Fresh',
    previewBg: '#ecfdf5',
    nodeColor: '#10b981',
    borderColor: '#047857',
    arrowColor: '#34d399',
    textColor: '#ffffff',
    decisionBg: '#ffffff',
    decisionBorder: '#047857',
    decisionText: '#047857',
  },
  crimson: {
    name: 'Crimson Wave',
    previewBg: '#fef2f2',
    nodeColor: '#dc2626',
    borderColor: '#991b1b',
    arrowColor: '#ef4444',
    textColor: '#ffffff',
    decisionBg: '#ffffff',
    decisionBorder: '#991b1b',
    decisionText: '#991b1b',
  },
  slate: {
    name: 'Slate Professional',
    previewBg: '#f8fafc',
    nodeColor: '#475569',
    borderColor: '#334155',
    arrowColor: '#64748b',
    textColor: '#ffffff',
    decisionBg: '#ffffff',
    decisionBorder: '#334155',
    decisionText: '#334155',
  },
  amber: {
    name: 'Amber Warmth',
    previewBg: '#fffbeb',
    nodeColor: '#d97706',
    borderColor: '#b45309',
    arrowColor: '#f59e0b',
    textColor: '#ffffff',
    decisionBg: '#ffffff',
    decisionBorder: '#b45309',
    decisionText: '#b45309',
  },
  teal: {
    name: 'Teal Calm',
    previewBg: '#f0fdfa',
    nodeColor: '#14b8a6',
    borderColor: '#0f766e',
    arrowColor: '#2dd4bf',
    textColor: '#ffffff',
    decisionBg: '#ffffff',
    decisionBorder: '#0f766e',
    decisionText: '#0f766e',
  },
  grape: {
    name: 'Grape Purple',
    previewBg: '#f5f3ff',
    nodeColor: '#8b5cf6',
    borderColor: '#6d28d9',
    arrowColor: '#a78bfa',
    textColor: '#ffffff',
    decisionBg: '#ffffff',
    decisionBorder: '#6d28d9',
    decisionText: '#6d28d9',
  },
  emerald: {
    name: 'Emerald Shine',
    previewBg: '#f0fdf4',
    nodeColor: '#059669',
    borderColor: '#047857',
    arrowColor: '#10b981',
    textColor: '#ffffff',
    decisionBg: '#ffffff',
    decisionBorder: '#047857',
    decisionText: '#047857',
  },
  fuchsia: {
    name: 'Fuchsia Burst',
    previewBg: '#fdf4ff',
    nodeColor: '#d946ef',
    borderColor: '#a21caf',
    arrowColor: '#e879f9',
    textColor: '#ffffff',
    decisionBg: '#ffffff',
    decisionBorder: '#a21caf',
    decisionText: '#a21caf',
  },
  indigo: {
    name: 'Indigo Deep',
    previewBg: '#eef2ff',
    nodeColor: '#6366f1',
    borderColor: '#4338ca',
    arrowColor: '#818cf8',
    textColor: '#ffffff',
    decisionBg: '#ffffff',
    decisionBorder: '#4338ca',
    decisionText: '#4338ca',
  },
  lime: {
    name: 'Lime Zest',
    previewBg: '#f7fee7',
    nodeColor: '#65a30d',
    borderColor: '#4d7c0f',
    arrowColor: '#84cc16',
    textColor: '#ffffff',
    decisionBg: '#ffffff',
    decisionBorder: '#4d7c0f',
    decisionText: '#4d7c0f',
  },
  sky: {
    name: 'Sky Blue',
    previewBg: '#f0f9ff',
    nodeColor: '#0ea5e9',
    borderColor: '#0284c7',
    arrowColor: '#38bdf8',
    textColor: '#ffffff',
    decisionBg: '#ffffff',
    decisionBorder: '#0284c7',
    decisionText: '#0284c7',
  },
  neo: {
    name: 'Neo Green',
    previewBg: '#f0fdf4',
    nodeColor: '#00d4aa',
    borderColor: '#00a085',
    arrowColor: '#00cec9',
    textColor: '#ffffff',
    decisionBg: '#ffffff',
    decisionBorder: '#00a085',
    decisionText: '#00a085',
  },
  neoDark: {
    name: 'Neo Dark',
    previewBg: '#0f172a',
    nodeColor: '#00d4aa',
    borderColor: '#00a085',
    arrowColor: '#00cec9',
    textColor: '#ffffff',
    decisionBg: '#1e293b',
    decisionBorder: '#00a085',
    decisionText: '#00cec9',
  },
  forestMermaid: {
    name: 'Forest Mermaid',
    previewBg: '#f0fdf4',
    nodeColor: '#22c55e',
    borderColor: '#16a34a',
    arrowColor: '#4ade80',
    textColor: '#ffffff',
    decisionBg: '#ffffff',
    decisionBorder: '#16a34a',
    decisionText: '#16a34a',
  },
  base: {
    name: 'Base',
    previewBg: '#f9fafb',
    nodeColor: '#6b7280',
    borderColor: '#374151',
    arrowColor: '#9ca3af',
    textColor: '#ffffff',
    decisionBg: '#ffffff',
    decisionBorder: '#374151',
    decisionText: '#374151',
  },
  neutral: {
    name: 'Neutral',
    previewBg: '#fafafa',
    nodeColor: '#737373',
    borderColor: '#525252',
    arrowColor: '#a3a3a3',
    textColor: '#ffffff',
    decisionBg: '#ffffff',
    decisionBorder: '#525252',
    decisionText: '#525252',
  },
  redux: {
    name: 'Redux',
    previewBg: '#faf5ff',
    nodeColor: '#764abc',
    borderColor: '#5b21b6',
    arrowColor: '#8b5cf6',
    textColor: '#ffffff',
    decisionBg: '#ffffff',
    decisionBorder: '#5b21b6',
    decisionText: '#5b21b6',
  },
  reduxDark: {
    name: 'Redux Dark',
    previewBg: '#1f1b2e',
    nodeColor: '#764abc',
    borderColor: '#5b21b6',
    arrowColor: '#8b5cf6',
    textColor: '#ffffff',
    decisionBg: '#2d1b69',
    decisionBorder: '#5b21b6',
    decisionText: '#8b5cf6',
  },
  // New modern themes with better contrast
  modern: {
    name: 'Modern Gradient',
    previewBg: '#f8fafc',
    nodeColor: '#6366f1',
    borderColor: '#4f46e5',
    arrowColor: '#8b5cf6',
    textColor: '#ffffff',
    decisionBg: '#ffffff',
    decisionBorder: '#4f46e5',
    decisionText: '#4f46e5',
  },
  corporate: {
    name: 'Corporate Blue',
    previewBg: '#f1f5f9',
    nodeColor: '#1e40af',
    borderColor: '#1e3a8a',
    arrowColor: '#3b82f6',
    textColor: '#ffffff',
    decisionBg: '#ffffff',
    decisionBorder: '#1e3a8a',
    decisionText: '#1e3a8a',
  },
  creative: {
    name: 'Creative Orange',
    previewBg: '#fff7ed',
    nodeColor: '#ea580c',
    borderColor: '#c2410c',
    arrowColor: '#fb923c',
    textColor: '#ffffff',
    decisionBg: '#ffffff',
    decisionBorder: '#c2410c',
    decisionText: '#c2410c',
  },
  nature: {
    name: 'Nature Green',
    previewBg: '#f0fdf4',
    nodeColor: '#16a34a',
    borderColor: '#15803d',
    arrowColor: '#22c55e',
    textColor: '#ffffff',
    decisionBg: '#ffffff',
    decisionBorder: '#15803d',
    decisionText: '#15803d',
  },
  royal: {
    name: 'Royal Purple',
    previewBg: '#faf5ff',
    nodeColor: '#7c3aed',
    borderColor: '#6d28d9',
    arrowColor: '#a855f7',
    textColor: '#ffffff',
    decisionBg: '#ffffff',
    decisionBorder: '#6d28d9',
    decisionText: '#6d28d9',
  },
  lavender: {
    name: 'Lavender',
    previewBg: '#faf5ff',
    nodeColor: '#a855f7',
    borderColor: '#9333ea',
    arrowColor: '#c084fc',
    textColor: '#ffffff',
    decisionBg: '#ffffff',
    decisionBorder: '#9333ea',
    decisionText: '#9333ea',
  },
};

// Default theme values
export const DEFAULT_MERMAID_THEME = MERMAID_COLOR_THEMES.default;

